name: Terraform

on:
  push:
    branches:
      - feature/rambabu2026
    paths:
      - "modules/**"
      - "envs/**"
      - ".github/workflows/**"

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan - DEV
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: oidc
          allow-no-subscriptions: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: envs/dev
        env:
          ARM_USE_OIDC: true
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform init

      - name: Terraform Validate
        working-directory: envs/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: envs/dev
        env:
          ARM_USE_OIDC: true
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_resource_group_name: rg-terraform-dev
          TF_VAR_admin_password: ${{ secrets.TF_ADMIN_PASSWORD }}
        run: terraform plan -input=false
